### ISSUE TITLE
Unstable recognition of marker

### ISSUE THREAD

**Issue by Konfupanda** [artoolkit/arunity5#82] opened 2016-06-04 17:19 UTC
I tried using the example cube marker image in my Unity project. The problem is, that when the main marker of the cube is facing the camera, the tracking is very unstable and it either completely disappears or rotates mutliple times per second. I tried calibrating the camera, but it did not help.

**Comment by OptrixAU** [comment] 2016-06-14 23:09
I have a similar issue on Windows. Oddly, there's no problem at all on Android and iOS.

If you're planning on building on mobile, build on that platform and take a look.

**Comment by ThorstenBux** [comment] 2016-06-23 00:03
I'm closing this because I cannot reproduce.

Feel free to ping again if you haven't resolved it jet. Also you can ask the forum at: http://artoolkit.org/community/forums/viewforum.php?f=28

**Closed by ThorstenBux** 2016-06-23 00:03 UTC
